apiVersion: web.servers.org/v1alpha1
kind: WebServer
metadata:
  name: tomcatdemo
spec:
  applicationName: tomcat-demo
  replicas: 3
  webImage:
    applicationImage: quay.io/jfclere/tomcat10:latest
    webApp:
      sourceRepositoryURL: https://github.com/jfclere/demo-webapp
      # where to put the built image (you need to have set the right default secrets).
      webAppWarImage: quay.io/jfclere/tomcat-demo
      builder:
        image: quay.io/jfclere/image-builder-jws
